//title
export const TITLE_HOME_PAGE = "آکادمی کدنویسی بحر"
export const TITLE_SERVICES = "خدمات ما "
export const TITLE_SELECTING = "دسته‌بندی‌ها"
export const TITLE_RESPONSE = "انتقادات و پیشنهادات"
export const TITLE_NAME_USER = "نام کاربر"
export const TITLE_EMAIL_USER = "ایمیل کاربر"
export const TITLE_DESCRIPT_MESSAGE = "متن پیام"
export const TITLE_LOGIN_USER = "ورود کاربر"
export const TITLE_PASS = "رمز عبور"
export const TITLE_PHONE = "شماره تماس"
export const TITLE_NATIONAL_CODE = "شماره ملی"
export const TITLE_BIRTHDAY = "تاریخ تولد"
export const TITLE_AGAIN_PASS = "بازیابی رمز عبور"
export const TITLE_COURSES = "لیست تمام دوره‌ها"
export const TITLE_NEWS = "لیست تمام اخبار و مقالات "
export const TITLE_COMMENTS = "نظرات کاربران"
export const TITLE_TEXT_COMMENT = "متن نظر"
export const TITLE_DETAIL_COURSE = "توضیحات دوره"
export const TITLE_EMAIL = "ایمیل"
export const TITLE_NAME = "نام کاربری"
export const TITLE_CURRENT_PASS = "رمز عبور فعلی"
export const TITLE_NEW_PASS = "رمز عبور جدید"
export const TITLE_AGAIN_NEW_PASS = "تکرار رمز عبور"
export const MAIN_HOME_INTRO = "برای یادگیری کامل و اصولی برنامه‌نویسی به همراه اساتید مجرب، با ما همراه شوید."
export const TITLE_NEWS_HOME = "اخبار و مقالات"
export const TITLE_BEST_TEACHER = "اساتید برتر"
export const SEND_EMAIL = "ارسال ایمیل"

//header
export const HEADER_HOME = "خانه"
export const HEADER_COURSE = "دوره‌ها"
export const HEADER_NEWS = " اخبار و مقالات"
export const HEADER_SERVICES = "خدمات"
export const HEADER_CONTACT = "ارتباط با ما"



//btn
export const START_LEARN = "شروع یادگیری"
export const SHOW_COURSE = 'مشاهده دوره‌ها'
export const MORE_COURSE = "لیست کامل دوره‌ها ..."
export const MORE_NEWS = "لیست کامل اخبار و مقالات ..."
export const INSERT_MESSAGE = "ثبت پیام"
export const LOGIN = "ورود"
export const SIGN_UP = "ثبت نام"
export const FORGET_PASS = "رمز عبورم را فراموش کرده‌ام!"
export const REMEMBER_ME = "مرا به خاطر بسپار!"
export const SUCESS_EMAIL = "تایید ایمیل"
export const INSERT_COMMENT = "ثبت نظر"
export const INSERT_NEW_CHANGES = "ثبت تغییرات"
export const IGNORE_NEW_CHANGES = "لغو تغییرات"
export const PAY = "پرداخت"
export const SHOW_MORE = "نمایش جزئیات"
export const PLACEHOLDER_BTN = "جهت عضویت در خبرنامه، ایمیل خود را وارد نمایید."
export const REMOVE_PHOTO = "حذف عکس"
export const EDIT_PHOTO = "تغییر عکس"
export const OPTIOANL_PHOTO = "آپشن"

export const ADDRESS = "ساری، جاده دریا، بعد از دنیای آرزو، پژوهشگاه سپهر "

//card name
export const COUNSELING = "مشاوره"
export const DEGREE = "مدرک معتبر"
export const EXAM = "امتحان"
export const HIRING = "استخدام"
export const ARCHITECTURE = "معماری"
export const PHYSICS = "فیزیک"
export const MATH = "ریاضی"
export const ELECTRICITY = "برق"
export const COMPUTER = "کامپیوتر"
export const CHEMISTRY = "شیمی"
export const INDUSTRY = "صنعت"
export const STOCK = "بازار سهام"
export const ATRICHE_TITLE = "عنوان مقاله"

//warning
export const SHARED_SYSTEM = "برای سیستم‌های اشتراکی توصیه نمی‌شود."

//detailcourse
export const OPACITY_COURSE = "ظرفیت دوره:"
export const NUMBER_STUDENT = "دانشجویان دوره:"
export const DURING_COURSE = "مدت دوره:"
export const TIME_START = "زمان شروع:"
export const PRICE_COURSE = "شهریه دوره:"
export const OFF_COURSE = "تخفیف هزینه دوره"

//english
export const TITLE_HOME_PAGE_EN = "Bahr Coding Academy"
export const MAIN_HOME_INTRO_EN = "Join us to learn the basics of programming with experienced teachers."
export const START_LEARN_EN = "Start Learning"
export const SHOW_COURSE_EN = 'View Courses'
export const HEADER_HOME_EN = "Home"
export const HEADER_COURSE_EN = "Courses"
export const HEADER_NEWS_EN = "News"
export const HEADER_SERVICES_EN = "Services"
export const HEADER_CONTACT_EN = "Contact us"
export const TITLE_SERVICES_EN = "My Services"

export const COUNSELING_EN = "Counseling"
export const DEGREE_EN = "valid certificate"
export const EXAM_EN = "Exam"
export const HIRING_EN = "Recruitment"
export const ARCHITECTURE_EN = "architecture"
export const PHYSICS_EN = "physics"
export const MATH_EN = "Math"
export const ELECTRICITY_EN = "Electricity"
export const COMPUTER_EN = "Computer"
export const CHEMISTRY_EN = "chemistry"
export const INDUSTRY_EN = "industry"
export const STOCK_EN = "Stock"
export const TITLE_SELECTING_EN = "Categories"
export const SHOW_MORE_EN = "more detail"
export const MORE_COURSE_EN = "...Full list of courses"
export const TITLE_NEWS_HOME_EN = "News and Articles"
export const ATRICHE_TITLE_EN = "Title"
export const MORE_NEWS_EN = "...Complete list of news and articles"
export const TITLE_BEST_TEACHER_EN = "Top Professors"
export const TITLE_RESPONSE_EN = "Critics and Suggestions"
export const TITLE_NAME_USER_EN = "User name"
export const TITLE_EMAIL_USER_EN = "User Email"
export const TITLE_DESCRIPT_MESSAGE_EN = "message text"
export const INSERT_MESSAGE_EN = "Send"
export const SEND_EMAIL_EN = "Send Email"
export const PLACEHOLDER_BTN_EN = "Enter your email to subscribe to the newsletter."
export const ADDRESS_EN = "Sari, Darya Road, after Arzoo World, Sepehr Research Institute"


